name: Android Cloud Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Жоба кодтарын серверге көшіру
      uses: actions/checkout@v4

    - name: Java ортасын дайындау
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Gradle ортасын баптау және APK жинау
      run: |
        echo "[*] Кодтардан қолданба құрастырылуда..."
        # Егер бұл нағыз Android Studio жобасы болса, ./gradlew арқылы жиналады
        chmod +x ./gradlew
        ./gradlew assembleDebug
        
    - name: Дайын қолданбаны шығару
      uses: actions/upload-artifact@v4
      with:
        name: Nexus-VIP-App
        # Дайын болған APK файлын іздеп, парақшаның астына қояды
        path: app/build/outputs/apk/debug/*.apk
